### ISSUE TITLE
Lint over the entire repository

### ISSUE THREAD

**Issue by mihaimaruseac** [sigstore/model-transparency#231]
Currently, some of the linting only happens for the model signing part of the repository, only for the new files for the API (e.g., the pytype linting). We should cover all of the codebase.

**Comment by spencerschrock** [comment]
Briefly used `ruff` to address an import ordering comment left during code review. It seems nice and configurable, and the options that match our current import ordering would be:

```toml
[lint.isort]
force-single-line = true
force-sort-within-sections = true
single-line-exclusions = ["collections.abc", "typing"]
```
